apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30005

---

apiVersion: v1
kind: Service
metadata:
  name: projeto-app-php-loadbalancer
spec:
  selector:
    app: projeto-app-php
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer