apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto2-app-deployment
  labels:
    app: projeto2-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: projeto2-app
  template:
    metadata:
      labels:
        app: projeto2-app
    spec:
      containers:
      - name: projeto2-app
        image: guilhermesantos21/projeto2-app:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80