apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dados
  labels:
    type: mysql-dados
spec:
  storageClassName: manual
  capacity: 
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /meubanco/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: guilhermesantos21/projeto2-mysql:1.6
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: my-secret
                key: ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom: 
              secretKeyRef:
                name: my-secret
                key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-dados
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-dados
        persistentVolumeClaim:
          claimName: mysql-dados