apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30005

---

apiVersion: v1
kind: Service
metadata:
  name: projeto2-app-loadbalancer
spec:
  selector:
    app: projeto2-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: LoadBalancer